name: 📦 Package (Windows + Linux)

on:
  push:
    tags:
      - v\d+.\d+.\d+
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]

    name: Build (windows-${{ matrix.arch }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup-windows
        with:
          arch: ${{ matrix.arch }}

      - name: Configure
        uses: ./.github/actions/cmake-configure
        with:
          platform: windows-clangcl
          arch: ${{ matrix.arch }}
          args: >
            -DCMAKE_INSTALL_PREFIX=dist
            -DGDJ_INSTALL_DEBUG_SYMBOLS=TRUE

      - name: Build (non-editor)
        uses: ./.github/actions/cmake-build
        with:
          platform: windows-clangcl
          arch: ${{ matrix.arch }}
          editor: false
          config: distribution

      - name: Build (editor)
        uses: ./.github/actions/cmake-build
        with:
          platform: windows-clangcl
          arch: ${{ matrix.arch }}
          editor: true
          config: distribution

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.arch }}
          path: ./dist/**
          retention-days: 1

  linux:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]

    name: Build (linux-${{ matrix.arch }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup-linux
        with:
          toolchain: llvm

      - name: Configure
        uses: ./.github/actions/cmake-configure
        with:
          platform: linux-clang
          arch: ${{ matrix.arch }}
          args: >
            -DCMAKE_INSTALL_PREFIX=dist
            -DGDJ_INSTALL_DEBUG_SYMBOLS=TRUE

      - name: Build (non-editor)
        uses: ./.github/actions/cmake-build
        with:
          platform: linux-clang
          arch: ${{ matrix.arch }}
          editor: false
          config: distribution

      - name: Build (editor)
        uses: ./.github/actions/cmake-build
        with:
          platform: linux-clang
          arch: ${{ matrix.arch }}
          editor: true
          config: distribution

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: linux-${{ matrix.arch }}
          path: ./dist/**
          retention-days: 1
  upload:
    runs-on: ubuntu-22.04
    needs: [windows, linux]

    name: Upload

    steps:
      - name: Download builds (windows-x64)
        uses: actions/download-artifact@v3
        with:
          name: windows-x64
          path: ./dist

      - name: Download builds (windows-x86)
        uses: actions/download-artifact@v3
        with:
          name: windows-x86
          path: ./dist

      - name: Download builds (linux-x64)
        uses: actions/download-artifact@v3
        with:
          name: linux-x64
          path: ./dist

      - name: Download builds (linux-x86)
        uses: actions/download-artifact@v3
        with:
          name: linux-x86
          path: ./dist

      - name: Delete temporary artifacts
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            windows-x64
            windows-x86
            linux-x64
            linux-x86
            macos

      - name: Separate debug symbols
        run: >
          rsync ./dist/./ ./symbols
          --archive
          --relative
          --remove-source-files
          --include="*/"
          --include="*.pdb"
          --include="*.debug"
          --include="*.dSYM/**"
          --exclude="*"

      - name: Delete empty directories
        run: find . -type d -empty -delete

      - name: Upload builds
        uses: actions/upload-artifact@v3
        with:
          name: godot-jolt_${{ github.ref_name }}
          path: ./dist/**
          retention-days: 1

      - name: Upload debug symbols
        uses: actions/upload-artifact@v3
        with:
          name: godot-jolt_${{ github.ref_name }}_symbols
          path: ./symbols/**
          retention-days: 1
